"""
Research-oriented extensions: skew corners, shell density profiling, grid export,
and a minimal non-abelian (cyclic subgroup of S_n) lift — companion to arXiv:2504.07006-style discussion.

This module does not prove new bounds; it instruments constructions for experiments.
"""

from __future__ import annotations

import csv
import json
from typing import Iterable, Iterator, List, Optional, Sequence, Set, Tuple

import behrend_corner_free as b

Coord = Tuple[int, int]

SkewWitness = Tuple[Coord, Coord, Coord, int, int]


def find_skew_corner(points: Set[Coord]) -> Optional[SkewWitness]:
    """
    Skew axis corner: (x,y), (x+d,y), (x,y+d') all in P with d != d' and d,d' != 0.

    This relaxes the standard corner where d = d'. Finding skew corners is an
    intermediate difficulty step in some corners-theory narratives (paper §2.2 style).
    """
    if len(points) < 3:
        return None
    by_row: dict[int, Set[int]] = {}
    by_col: dict[int, Set[int]] = {}
    for x, y in points:
        by_row.setdefault(y, set()).add(x)
        by_col.setdefault(x, set()).add(y)

    for x, y in points:
        for xp in by_row.get(y, ()):
            if xp == x:
                continue
            d = xp - x
            if d == 0:
                continue
            for yp in by_col.get(x, ()):
                if yp == y:
                    continue
                dp = yp - y
                if dp != 0 and d != dp:
                    return ((x, y), (xp, y), (x, yp), d, dp)
    return None


def iter_shell_counts(
    d: int, k: int, max_x: Optional[int] = None
) -> Iterator[Tuple[int, int]]:
    """Yield (sum_sq, population count) for each shell."""
    if max_x is None:
        max_x = d**k - 1
    max_sum_sq = k * (d - 1) ** 2
    for sum_sq in range(max_sum_sq + 1):
        n = sum(1 for _ in b.iter_sphere_slice(max_x, k, d, sum_sq))
        yield sum_sq, n


def shell_density_rows(d: int, k: int, max_x: Optional[int] = None) -> List[Tuple[int, int]]:
    return list(iter_shell_counts(d, k, max_x=max_x))


def write_shell_profile_csv(path: str, d: int, k: int, max_x: Optional[int] = None) -> None:
    """CSV columns: sum_sq, count, density_fraction (relative to d^k universe)."""
    if max_x is None:
        max_x = d**k - 1
    denom = max_x + 1
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["sum_sq", "count", "density_fraction"])
        for sum_sq, cnt in iter_shell_counts(d, k, max_x=max_x):
            w.writerow([sum_sq, cnt, cnt / denom])


def export_sparse_grid_csv(points: Iterable[Coord], path: str, meta: Optional[dict] = None) -> None:
    """One row per occupied cell: x,y. Optional JSON sidecar if meta ends with .csv → .meta.json."""
    pts = sorted(points)
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["x", "y"])
        for x, y in pts:
            w.writerow([x, y])
    if meta is not None:
        side = path.rsplit(".", 1)[0] + ".meta.json"
        with open(side, "w", encoding="utf-8") as f:
            json.dump(meta, f, indent=2)


def export_run_json(
    path: str,
    *,
    mode: str,
    params: dict,
    points: Sequence[Coord],
    one_d_sorted: Optional[Sequence[int]] = None,
) -> None:
    """Pipe-friendly JSON for external grid-norm / detection tooling."""
    payload = {
        "format": "behrend_corner_free_grid_v1",
        "mode": mode,
        "parameters": params,
        "grid_points": [{"x": x, "y": y} for x, y in sorted(points)],
        "cardinality": len(points),
    }
    if one_d_sorted is not None:
        payload["one_d_shell"] = list(one_d_sorted)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)


def cyclic_permutation_from_integer(x: int, n: int) -> List[int]:
    """
    Image of x in the cyclic subgroup of S_n generated by (0 1 ... n-1):
    position i maps to (i + x) mod n as labels 0..n-1.

    This is a concrete non-abelian setting (n>=3) alongside abelian Z/nZ lifts.
    Section 1.1-style reductions to all finite groups are proved in the paper;
    this helper is only a pedagogical embedding.
    """
    if n < 2:
        raise ValueError("n must be >= 2")
    r = x % n
    return [(i + r) % n for i in range(n)]


def lift_shell_to_symmetric_group_json(
    shell_values: Sequence[int],
    n_perm: int,
    path: str,
    *,
    extra: Optional[dict] = None,
) -> None:
    """Write JSON list of {value, permutation} for each element of the shell."""
    rows = []
    for v in shell_values:
        rows.append(
            {
                "value": int(v),
                "cyclic_permutation_S_n": cyclic_permutation_from_integer(v, n_perm),
            }
        )
    out = {"lift": "cyclic_subgroup_S_n", "n_perm": n_perm, "elements": rows}
    if extra:
        out["extra"] = extra
    with open(path, "w", encoding="utf-8") as f:
        json.dump(out, f, indent=2)


def write_shell_density_svg(
    path: str,
    d: int,
    k: int,
    max_x: Optional[int] = None,
    w: int = 820,
    h: int = 320,
) -> None:
    """Bar-style SVG of shell population vs sum_sq (stdlib only)."""
    if max_x is None:
        max_x = d**k - 1
    rows = shell_density_rows(d, k, max_x=max_x)
    counts = [c for _, c in rows]
    max_c = max(counts) if counts else 1
    pad_l, pad_r, pad_t, pad_b = 50, 30, 35, 55
    iw, ih = w - pad_l - pad_r, h - pad_t - pad_b
    nbar = len(rows) if rows else 1

    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" '
        f'viewBox="0 0 {w} {h}" font-family="system-ui,sans-serif">',
        '<rect width="100%" height="100%" fill="#fafafa"/>',
        f'<text x="{w//2}" y="22" text-anchor="middle" font-size="14" fill="#222">'
        f"Shell density |{{x : Σ x_i² = S}}| vs S (d={d}, k={k})</text>",
    ]
    bw = max(0.8, iw / nbar - 0.4)
    for i, (_S_val, cnt) in enumerate(rows):
        if cnt == 0:
            continue
        bh_bar = (cnt / max_c) * ih
        x0 = pad_l + i * (iw / nbar)
        y0 = pad_t + ih - bh_bar
        parts.append(
            f'<rect x="{x0:.2f}" y="{y0:.2f}" width="{bw:.2f}" height="{bh_bar:.2f}" '
            f'fill="#5e81ac" opacity="0.85"/>'
        )
    parts.append(
        f'<text x="{pad_l}" y="{h-18}" font-size="11" fill="#555">S (sum of squared digits)</text>'
    )
    parts.append(
        f'<text x="{w//2}" y="{h-8}" text-anchor="middle" font-size="10" fill="#888">'
        f"max count per shell = {max_c}</text>"
    )
    parts.append("</svg>")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(parts))
